### ISSUE TITLE
Train/val/test split for HumanAct12

### ISSUE THREAD

**Issue by fabienbaradel** [Mathux/ACTOR#11]
Hi,
Thanks for releasing your code. I am wondering what is the train/val/test split that you are using for HumanAct12? It seems that you are always using the entire dataset for training and evaluating if I am not mistaken..
Tanks for your feedback and your help.

**Comment by Mathux** [comment]
Hi,
There is no train/val/test split for NTU-13 and HumanAct12. I am using the same configuration as the authors of Action2Motion (which is the same team as the authors of the HumanAct12 dataset).

**Comment by fabienbaradel** [comment]
Thanks for your feedback, so what kind of criterion are you using for training the classifier to make sure that you are not overfitting?

**Comment by Mathux** [comment]
I did not train these two classifier myself, I used the pre-trained provided by the authors of Action2Motion https://github.com/EricGuo5513/action-to-motion (to get comparable results on NTU13 and HumanAct12, as it is used in the evaluation). I don't know what criteria they used to train it, you can ask them. 

As this classifier is not used while training ACTOR, it might not be a real issue. The evaluation shows that, with this classifier and a given action, our generated motions have "motion features" similar to those of the ground truth.

**Comment by fabienbaradel** [comment]
Ok thanks a lot for these details :)
