### ISSUE TITLE
Adding clothes or skin

### ISSUE THREAD

**Issue by sard0r** [Mathux/ACTOR#14]
Hello Dear Author. Thank you very much for your good work. I wanted to ask if there is a way to add clothes, skin, background to these 3d actions.

Thank you very much,

Sardor

**Comment by Mathux** [comment]
Hello @sard0r, 

The ACTOR model generates motion in SMPL format. So you get vertices with a fixed topology.  Please check the literature about clothing with SMPL. This is a bit out of scope of this project.
