### ISSUE TITLE
How can i input the output data of decoder into input data of decoder?

### ISSUE THREAD

**Issue by SinDongHwan** [Mathux/ACTOR#15]
I want to expand output length like following method,
i.e. run decoder twice. 
Because i think if i only expand length from 60 to 120 lengths, meaningless output will be generated after 60th frame.

If i generate 120 length(60 length *2)
input -> decoder -> output(60 length) -> input -> decoder -> output(60 length) 
 => total 120 length.

**Comment by Mathux** [comment]
Hello,

What type of action do you want to generate? A cycling action (jumping jack for example) or an "atomic" action (sit/throw/drink)?

In the first case, I would generate the action several time (60 frames x3 [a, b, c]) and then try to "glue" them together by finding the closest match of the end of a into b, and same from end of b to c. Then you can do little interpolation (or motion infilling) between the two parts.

In the second case, same idea, but this can be more difficult.
First, you don't want to lose the beginning of the action (b). Second, the action can change the "state" of the body. To give an example, It does not make so much sense to ask for a sitting action twice in a row (without asking for a standing action in between).

**Comment by SinDongHwan** [comment]
Hellp, @Mathux 
Thank you for replying.

I want to generate the actions both a cycling action(jumping jack for example) and "atomic" action(sit/throw/drink).

When i read "Figure 2: Method Overview" in your paper, I thought I would insert the end pose vector of the first motion and action category as input transformer encoder for integration motions . 
But when i run  "generation motion " example code, i found out that done by putting random values in the decoder without encoding.

Is my understanding correct?

if correct, how do i insert pose vector and action category as input encoder?

**Comment by Mathux** [comment]
Hello,
> When i read "Figure 2: Method Overview" in your paper, I thought I would insert the end pose vector of the first motion and action category as input transformer encoder for integration motions .

No, ACTOR model generates the motion entirely from scratch (it does not depends on the first frame). At test time, the latent vector z, is sampled from a Gaussian distribution and the decoder (generator) does not take any pose vector as input. 

> if correct, how do i insert pose vector and action category as input encoder?

In the current architecture, there is no way of doing it. I suggest to try to "transition" between actions by using a motion infilling network.
