### ISSUE TITLE
Question for embedding dimension

### ISSUE THREAD

**Issue by JosephKKim** [Mathux/ACTOR#16]
Thanks for the wonderful work @Mathux!
I really enjoyed reading paper and also testing it on my environment, 
while looking at your code and paper, I found out that you've set dimensionality of embedding for VAE to 256 and I'm wondering if there's any reason for this.

Thanks, 
Joseph

**Comment by Mathux** [comment]
Hello @JosephKKim,

Yes, the dimensionality of the latent space is fixed at 256. This exact number is a bit arbitrary, but the intuition may be that it corresponds to a "motion embedding". So, in my opinion, it should be larger than a simple "pose embedding". Some papers use 64 or 128 for pose embedding, so I just took the next higher power of two.

Feel free to experiment with another value if you wish :)

**Comment by JosephKKim** [comment]
Thank you so much for the fast reply... I didn't expect that I would get a reply this fast.. :) 
Okay, I see your point that "motion" would need more embedding dimension than that of the pose.
I was trying to improve ACTOR by using properties from VAEs.. so that was my motivation for this issue. 

Once again, thank you so much!

P.S. I've also enjoyed your paper TEMOS (Congrats!), since I've read MotionCLIP paper and wondered how you and your group will make use of other modalities.
