### ISSUE TITLE
Reproduce `gru` and `fc`

### ISSUE THREAD

**Issue by GuyTevet** [Mathux/ACTOR#17]
Hi @Mathux !
Can you share with us the training commands reproducing the `gru` and `fc` models reported in your paper? Thanks:)

**Comment by Mathux** [comment]
Hello,

You just need to change the architecture name from transformer to gru of fc. So the modelname can be:
- cvae_transformer_rc_rcxyz_kl
- cvae_gru_rc_rcxyz_kl
- cvae_fc_rc_rcxyz_kl
