### ISSUE TITLE
Custom Training/Inference Data

### ISSUE THREAD

**Issue by mahdiabdollahpour** [Mathux/ACTOR#18]
Hi

Thanks for the repo and the documentation!

How can I create .pkl files for a custom dataset to train models on or evaluate current models on them?

**Comment by Mathux** [comment]
Hello @mahdiabdollahpour,

You don't necessarily need to create .pkl files. You need to create a python file in the [src/datasets/](https://github.com/Mathux/ACTOR/tree/master/src/datasets) folder that corresponds to your custom dataset. Then you take inspiration from ``ntu.py`` or ``uestc.py``, but load your data instead. So you can use .pkl, .npy, or any other format as long as you use the right function to load them.

Then when it is done, edit the file  [src/datasets/get_datasets.py](https://github.com/Mathux/ACTOR/tree/master/src/datasets/get_dataset.py) to add your dataset. Then it should be usable by the other scripts.
