### ISSUE TITLE
Question about interpolation in latent space

### ISSUE THREAD

**Issue by WinstonDeng** [Mathux/ACTOR#4]
Hi, thanks for your great work!
I'm interested in concatenating two actions using your model. But I'm not sure what's means of "interpolation in latent space".
Could you give more details or some guidance?

**Comment by Mathux** [comment]
Hello,

> I'm interested in concatenating two actions using your model.

ACTOR is unfortunately limited to one action at a time.
If you want to concatenate multiple actions, you can try to put them together using interpolation methods, or with motion inbetweening/infilling methods (but with no guarantee of having something that works well).

You can also try to extend the method to deal with a sequence of actions, but I think it is not obvious how to do that, and train such a model.

> But I'm not sure what's means of "interpolation in latent space".

In our latent space, a latent vector (given an action) can be decoded into an entire sequence. Given 2 latent vectors (v1 and v2) and an action A, if we decode the latent vectors into motions (m1 and m2), we will have 2 motions that represent the action (two different styles/ways of doing the action). So when we say "interpolation in the latent space", it means that if we take v = alpha*v1 + (1-alpha)*v2, this new latent vector can be decoded into a movement, which the "style" will be a mixture of m1 and m2.
