### ISSUE TITLE
GLError  during render motions

### ISSUE THREAD

**Issue by wang-zm18** [Mathux/ACTOR#6]
Hello,Mathux!   Thanks for your implementation. When I tried to render motions with generation.npy， the error occurs like the following. I have tried the introduction in this link https://github.com/mmatl/pyrender/issues/86, but it does not work. Thank you in advance!
![image](https://user-images.githubusercontent.com/47704679/142171831-f1916f9b-a123-42f7-a9a1-38421267ebdf.png)

**Comment by Mathux** [comment]
Hello Wang,
I am not a specialist in this area but I can try to help. I have some questions for you:
- Do you have a GPU in your device?
- Do you have a display attached to your computer or is it in a server?
- What driver are you using for OpenGL? Mesa or Nvidia or something else?

**Comment by wang-zm18** [comment]
Thank you Mathux! I use GeForce RTX 2080 Gpus, and my driver is nvidia 460 and I run this command in my server.

**Comment by wang-zm18** [comment]
I just tried "MESA_GL_VERSION_OVERRIDE=4.1 python -m src.render.rendermotion pretrained_models/humanact12/generation.npy" as the link said, it works! Thank you for all the same!

**Comment by ChenFengYe** [comment]
> Hello Wang, I am not a specialist in this area but I can try to help. I have some questions for you:
> 
> * Do you have a GPU in your device?
> * Do you have a display attached to your computer or is it in a server?
> * What driver are you using for OpenGL? Mesa or Nvidia or something else?

Hi, I meet the same error, but "MESA_GL_VERSION_OVERRIDE=4.1" does not work. 
> * a GPU
> * no display, it is a server
> * I think my GPU driver is nvidia 450.102.04. 

I also try `os.environ['PYOPENGL_PLATFORM'] = 'osmesa'`, but get error
> AttributeError: 'GLXPlatform' object has no attribute 'OSMesa'

Thank you @Mathux  !
