### ISSUE TITLE
shake in the later sequence

### ISSUE THREAD

**Issue by bigpo** [Mathux/ACTOR#8]
Hi, @Mathux , Thanks for your nice work!
I encountered some issue when i generated some motion sequences.
Like the shake problem occurred about 60 frames later,  do you have any idea about it? thanks!

https://user-images.githubusercontent.com/9010202/144010246-35d2c693-5379-4452-9481-5c926c2ee8d0.mp4

https://user-images.githubusercontent.com/9010202/144010491-b71a6dd7-30ac-4383-905d-9c943c357a03.mp4

**Comment by Mathux** [comment]
Hello @bigpo 

1. How many frames did you train this model on? (or if you took the pretrained model, it is on a fixed size of 60 frames). 
2. How many frames are you testing it on? (60 frames or more?)

If you test with more frames than in the training, some problems can occur. You should instead fine-tuning it with variable duration (like explained in the paper).

**Comment by bigpo** [comment]
> 



> Hello @bigpo
> 
> 1. How many frames did you train this model on? (or if you took the pretrained model, it is on a fixed size of 60 frames).
> 2. How many frames are you testing it on? (60 frames or more?)
> 
> If you test with more frames than in the training, some problems can occur. You should instead fine-tuning it with variable duration (like explained in the paper).

I tested it on the pretrained model with more than 60 frames. Thanks for your reply.
